[tool.uv.workspace]
members = [
  "packages/common-py",
  "packages/schema",
  "packages/adapters",
  "packages/policy-engine",
  "packages/telemetry",
  "packages/runtime",
  "packages/sdk-python",
  "packages/cli"
]

[tool.uv.sources]
dockrion-common = { workspace = true }
dockrion-schema = { workspace = true }
dockrion-adapters = { workspace = true }
dockrion-policy = { workspace = true }
dockrion-telemetry = { workspace = true }
dockrion-runtime = { workspace = true }
dockrion-sdk = { workspace = true }
dockrion-cli = { workspace = true }

# Optional shared tool config
[tool.ruff]
line-length = 100
target-version = "py312"