[project]
name = "dockrion-common"
version = "0.1.1"
description = "Common utilities for Dockrion"
requires-python = ">=3.12"
dependencies = ["pydantic>=2.5"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
